# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-18 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_list_item_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='logtime',
        ),
        migrations.AddField(
            model_name='item',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
