# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_auto_20190523_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='logtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
