# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_item_logtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='logtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 6, 47, 58, 431271, tzinfo=utc), verbose_name='生成日期'),
        ),
    ]
