# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0017_auto_20190614_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
